<a href="https://colab.research.google.com/github/atheostheos/ML_2023/blob/main/02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашние задания

1. Создайте двумерный массив размером 5x5 и заполните его случайными целыми числами от 1 до 100. Найдите максимальное значение в каждой строке массива и выведите результат.

2. Создайте одномерный массив размером 100 и заполните его случайными числами от 1 до 100. Найдите все элементы массива, которые больше среднего значения элементов массива и замените их на 0.

3. Создайте два одномерных массива размером 10 и заполните их случайными числами от 1 до 100. Найдите скалярное произведение этих массивов и выведите результат.

4. Создайте двумерный массив размером 4x4 и заполните его случайными числами от 1 до 100. Используя функцию reshape(), преобразуйте массив в одномерный массив и отсортируйте его по возрастанию.

5. Создайте двумерный массив размером 6x6 и заполните его случайными числами от 1 до 100. Найдите все элементы массива, которые больше 50 и меньше 75, и замените их на 0.

6. Создайте одномерный массив размером 50 и заполните его случайными числами от 1 до 100. Используя функцию argmax(), найдите индекс максимального элемента массива и выведите результат.

7. Создайте два одномерных массива размером 10 и заполните их случайными числами от 1 до 100. Используя функцию dot(), выполните матричное умножение этих массивов и выведите результат.

8. Создайте одномерный массив размером 10 и заполните его случайными числами от 1 до 100. Запишите массив в файл "array.txt".

9. Создайте двумерный массив размером 5x5 и заполните его случайными числами от 1 до 100. Найдите максимальное значение в каждой строке массива и запишите результат в файл "max_values.txt".

10. Создайте двумерный массив размером 3x3 и заполните его случайными числами от 1 до 100. Замените все элементы массива, которые меньше 50, на -1, а все элементы, которые больше или равны 50, на 1. Запишите результат в файл "result.txt".

In [18]:
import numpy as np

print("Task 1")
a1 = np.random.randint(1,101,(5,5))
print(a)
print(a.max(axis=1))

print("\nTask 2")
a2 = np.random.randint(1,101,100)
print(a2)
a2_av = np.average(a2)
a2[a2 > a2_av] = 0
print(av)
print(a2)

print("\nTask 3")
a31 = np.random.randint(1,101,10)
a32 = np.random.randint(1,101,10)
print(np.dot(a31, a32))

print("\nTask 4")
a4 = np.random.randint(1,101,(4,4))
print(a4)
print(np.sort(a4.reshape(-1)))

print("\nTask 5")
a5 = np.random.randint(1,101,(6,6))
print(a5)
a5[(a5 > 50)&(a5 < 75)] = 0
print(a5)

print("\nTask 6")
a6 = np.random.randint(1,101,50)
print(a6.argmax())

print("\nTask 7")
a71 = np.random.randint(1,101,50)
a72 = np.random.randint(1,101,50)
print(np.dot(a71, a72))

print("\nTask 8")
a8 = np.random.randint(1,101,10)
np.savetxt("array.txt", a8)

print("\nTask 9")
a9 = np.random.randint(1,101,(5,5))
np.savetxt("max_values.txt", a9.max(axis=1))

print("\nTask 10")
a10 = np.random.randint(1,101,(3,3))
a10[a10 < 50] = -1
a10[a10 >= 50] = 1
np.savetxt("result.txt", a10)

Task 1
[[59 11 86 53 86]
 [ 2 37 75 39 50]
 [75 58 66 73 25]
 [28 69 59 33 43]
 [21 93 11 79 94]]
[86 75 75 69 94]

Task 2
[ 54  86  62  75   5   4  48  10   5  25  25  26  20  76 100  50   5  94
  30   9  20  69  93  56  97  12  83  31  66  86  56  79  51  24  38  11
  10  33  73  11  76  44  98  24  15  86  10  64  99  67   8  60  54  62
  71   7  89  25  47   7  38  74  11  93  25   5   7  44   6  88  73  77
  22  55  68   4  12  77  69  39  71  75  28  74  64  79  49  55 100  32
   5  84  45  73  36  83  15  16  33  95]
51.8
[ 0  0  0  0  5  4 48 10  5 25 25 26 20  0  0  0  5  0 30  9 20  0  0  0
  0 12  0 31  0  0  0  0  0 24 38 11 10 33  0 11  0 44  0 24 15  0 10  0
  0  0  8  0  0  0  0  7  0 25 47  7 38  0 11  0 25  5  7 44  6  0  0  0
 22  0  0  4 12  0  0 39  0  0 28  0  0  0  0  0  0 32  5  0 45  0 36  0
 15 16 33  0]

Task 3
21513

Task 4
[[39 82 53 80]
 [44  4 18 93]
 [80 18 91 87]
 [97  1 84 70]]
[ 1  4 18 18 39 44 53 70 80 80 82 84 87 91 93 97]

Task 5
[[ 49  80  86  55 